### ISSUE TITLE
Secret key exposed

### ISSUE THREAD

**Issue by henrybarklam** [ahmedlemine/pdf-merger#2]
Taking a look at the docker-compose.yml and seeing the SECRET_KEY under environment exposed. 

From the Django documentation: When you create a new Django project using startproject, the settings.py file is generated automatically and gets a random SECRET_KEY value. This value is the key to securing signed data – it is vital you keep this secure, or attackers could use it to generate their own signed values.

There's a good chance this is a key that is no longer in use or one that you've put up as a dummy variable, thought I'd let you know jic.

**Comment by ahmedlemine** [comment]
Thanks.
As you said, it's a dummy. I will add .env file for all sensitive variables.

**Comment by ahmedlemine** [comment]
Added django-environ and moved secret key and other env vars to .env.
User can refer to "example.env" file to create their own .env file.
